# Generated by Django 5.1.7 on 2025-07-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='updated_at',
        ),
    ]
