# Generated by Django 5.1.7 on 2025-07-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_vote_options_remove_vote_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='created_at',
        ),
        migrations.AddField(
            model_name='vote',
            name='voted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
